name: C/C++ CI macos

on:
  push:
    branches:
      - CI

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: change date in version
      run: sed "s/+UNKNOWN/_$(date '+%F')/" version.inc
    - name: mkdir in deps
      run: mkdir deps/build
    - name: cmake deps
      working-directory: ./deps/build
      run: cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13"
    - name: make deps
      working-directory: ./deps/build
      run: make
    - name: clean deps
      working-directory: ./deps/build
      run: rm -rf dep_*
    - name: mkdir build
      run: mkdir build
    - name: cmake
      working-directory: ./build
      run: cmake .. -DCMAKE_PREFIX_PATH="$PWD/../deps/build/destdir/usr/local" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13" -DSLIC3R_STATIC=1
    - name: make slic3r
      working-directory: ./build
      run: make slic3r
    - name: create directory and copy into it
      working-directory: ./build
      run: |
        mkdir Slic3r++
        mkdir Slic3r++/Slic3r++.app
        mkdir Slic3r++/Slic3r++.app/Contents
        mkdir Slic3r++/Slic3r++.app/Contents/_CodeSignature
        mkdir Slic3r++/Slic3r++.app/Contents/Frameworks
        mkdir Slic3r++/Slic3r++.app/Contents/MacOS
    - name: copy resources
      working-directory: ./build
      run: |
        cp -Rf ../resources Slic3r++/Slic3r++.app/Contents/Resources
        cp Slic3r++/Slic3r++.app/Contents/Resources/icons/Slic3r.icns Slic3r++/Slic3r++.app/Contents/resources/Slic3r.icns
        cp src/Info.plist Slic3r++/Slic3r++.app/Contents/Info.plist
        echo -n -e '\xff\xfeAPPL\x3f\x00\x3f\x00\x3f\x00\x3f\x00\x0a\x00' > PkgInfo
    - name: copy bin
      working-directory: ./build
      run: |
        cp -f src/slic3r++ Slic3r++/Slic3r++.app/Contents/MacOS/slic3r++
        chmod 777 Slic3r++/Slic3r++.app/Contents/MacOS/slic3r++
#    - name: signing resources (creating CodeResources inside _CodeSignature)
#      working-directory: .
#      run: codesign -s <identity> resources
# maybe i should just try to do that on a separate pc and copy the file here, more secure as a signing process.
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos
        path: build/Slic3r++/
